django-apps/cuestonario/cuestonario/urls.py
from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

django-apps/cuestonario/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='details'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('mapa/<int:total_score>', views.MapaView.as_view(), name='mapa'),
    path('mapa/add_location/', views.add_location, name='addlocation'),
    path('mapa/resultados', views.listaResultados , name="resultados"),
   
]

django-apps/cuestonario/polls/models.py
from django.db import models
from django.contrib import admin
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    score = models.IntegerField()
    answer = models.CharField(max_length=200)

    @admin.display(
        boolean=True,
        ordering='score',
        description='Value',
    )
    
    def __str__(self):
        return self.question_text
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text

class Users(models.Model):
    total_score = models.IntegerField(default=0)
    name = models.CharField(max_length=256, default="Nombre")
    latitude = models.CharField(max_length=500)
    longitude = models.CharField(max_length=500)
        
    def __str__(self):
        return self.name
    

django-apps/cuestonario/polls/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render 
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question, Users

user = Users()
def reset():
    global user
    user = Users()    

class IndexView(generic.TemplateView):
    template_name = 'polls/index.html'
    context_object_name = 'start_question'
    
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'

class MapaView(generic.TemplateView):
    model = Users
    template_name = 'polls/mapa.html'

class ResultadosView(generic.TemplateView):
    model = Users
    template_name = 'polls/resultados.html'        

def listaResultados(request):
    reset()
    points = list(Users.objects.values('id', 'latitude', 'longitude', 'total_score'))
    context = {'points':points}
    return render(request, 'polls/resultados.html', context)    
    
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        if str(selected_choice) == str(question.answer):
            user.total_score += int(str(question.score))
            print (user.total_score)
        else:
            print ("No entro")
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        if question.id == 5:
            return HttpResponseRedirect(reverse('polls:mapa', args=(user.total_score,)))
        else :
            return HttpResponseRedirect(reverse('polls:details', args=(question.id + 1,)))

def add_location(request):
    user.latitude = request.GET.get('lat')
    user.longitude = request.GET.get('long')
    user.save()
    reset()
    return 1

django-apps/cuestonario/polls/templates/polls/details.html
<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Cuestionario</title>
  </head>
  <body>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
            <div class="p-3 mb-2 bg-primary text-white">
            <legend><h1>{{ question.question_text }}</h1></legend></div>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <div class="form-check p-3 mb-2 bg-white text-dark" style="margin-left: 1em">
                    {% for choice in question.choice_set.all %}
                        <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                        <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                    {% endfor %}
            </div> 
        <div style="margin-left: 1em"> 
            
        <button class="fs-3 btn btn-primary" type="submit"> Siguiente </button> 
    </div> 
            
    </form>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

django-apps/cuestonario/polls/templates/polls/index.html
<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Cuestionario</title>
  </head>
  <body>
	<div style="position: absolute; top:1em; left:1em">
	<form action="{% url 'polls:details' '1' %}">
		<Button type="submit" class="btn btn-primary"> <h1>Empezar Cuestionario </h1></button>
	</form>

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

django-apps/cuestonario/polls/templates/polls/mapa.html
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>

    <title>Mapa</title>
  </head>
  <body>
    <div class="p-3 mb-2 bg-primary text-white" style="height:10%">
      <legend><h2>Seleccione una locaciòn en donde guardar su resultado: </h2></legend></div>
      <div id="map" style="height:75%; width:100%;"></div>
      <script type="text/javascript">
        var map = L.map('map').setView([23.7415532, -99.18144], 13);

        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
          maxZoom: 19,
          attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
      }).addTo(map);
      
        map.on('click', (e) =>{
          let lat = e.latlng.lat
          let long = e.latlng.lng
          L.marker([lat, long]).addTo(map)
          fetch(`add_location?lat=${lat}&long=${long}`)
         
        })
    </script>
    
    <form action="{% url 'polls:resultados' %}" method="post" style="margin-left:70%; width:30%; height:10%; margin-top:20px" >
      {% csrf_token %}
      <button class="btn btn-primary" type="submit" style="width:100%; height:100%"><h3>Ver Resultados</h3></button>
    </form>
	<!-- Optional JavaScript  -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

django-apps/cuestonario/polls/templates/polls/resultados.html
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
    
    <title>Mapa</title>
  </head>
  <body>

    <div class="p-3 mb-2 bg-primary text-white" style="height:17%">
        <legend><h2 id="resultado"></h2></legend><h3>A continuaciòn se muestran los demas resultados:</h3></div>
        <div id="map" style="height:83%; width:100%;"></div>
  
{{ points|json_script:"points_json" }}

    <script type="text/javascript">
        var map = L.map('map').setView([23.7415532, -99.1814], 13);

        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19, 
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            }).addTo(map);
        
        let points = JSON.parse(document.getElementById('points_json').textContent);
        document.getElementById("resultado").innerHTML = "Su resultado fue: " + points[points.length-1]["total_score"];
        points.forEach(points => {
            var marker = L.marker([points.latitude, points.longitude]);
            marker.bindPopup("Aqui fue guardada la puntuaciòn de: " + points.total_score);
            marker.addTo(map);

        });

        
    </script>
	<!-- Optional JavaScript  -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>